### PR TITLE
Add PyLibSuitETECSA

### PR DESCRIPTION
**Pull request by lesclaz**

### CODE REVIEW

**Comment by jlalfonso21** [comment]
I think all descriptions should be written in English

**Comment by lesclaz** [comment]
> I think all descriptions should be written in English

Ok, it's valid, but I'm still learning English, I don't master the technical language.

**Comment by lesclaz** [comment]
> I think all descriptions should be written in English

I'll try to translate it with google translator

**Comment by lesclaz** [comment]
> I think all descriptions should be written in English

and now?

**Pull request merged**
